/*
 * charging.h
 *
 *  Created on: Feb 17, 2026
 *      Author: ishanchitale
 */

#ifndef INC_CHARGING_H_
#define INC_CHARGING_H_

// TODO
// FOR THE CHARGING SEQUENCE, BAUD RATE MUST BE CHANGED TO 250 KBPS
// CHANGE PRESCALER FROM 20 TO 40; RESTART CAN PERIPHERAL AFTERWARD

// TODO
// ENTER ELCON CHARGING SEQUENCE OR J1772 CHARGING SEQUENCE

#endif /* INC_CHARGING_H_ */
